version: "3.8"

services:
  idfmi:
    build: ./app
    container_name: idfmi
    restart: always
    env_file: .env
    networks:
      - db_network
      - web_network
    depends_on:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - ./app/:/app/
# This is used to simulate the webcam, 
# should be used in linux virtual machine with access to webcam allowed      
#     devices: 
#       - /dev/video0:/dev/video0

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_DATA_DIR=/data/db
      - MONGODB_LOG_DIR=/dev/null
    networks:
      - db_network
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - web_network
    depends_on:
      - idfmi
    ports:
      - 80:80

networks:
  db_network:
  web_network:

volumes:
  mongodbdata:
